services:
  - type: web
    name: trip-ticket
    runtime: php  # Changed from 'env' to 'runtime'
    plan: free
    envVars:
      - key: PHP_VERSION
        value: "8.1"
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
    startCommand: heroku-php-apache2 public/
